module Blizzard
  module Api
    module Profile
      class CharacterProfileSummary < BaseRequest
        def self.fetch: (
          region: String,
          name: String,
          realm: String,
          ?locale: String,
          ?params: Hash[Symbol, untyped]
        ) -> Hash[Symbol, untyped]
      end
    end
  end
end
