module Blizzard
  module Api
    module GameData
      class TalentMedia < Blizzard::Api::BaseRequest
        def self.fetch: (
          blizzard_id: Integer,
          ?region: String
        ) -> Hash[Symbol, untyped]
      end
    end
  end
end
